In [11]:
import numpy as np # Импорт библиотеки NumPy с общепринятым сокращением.

In [14]:
a = np.array([3,2,1]) # Создание массива из обычных списков;
matrix = np.eye(3,3) # Создание массива-единичной матрицы;
ones = np.ones((2,5)) # Создание массива из единиц;
zeros = np.zeros((6,1))
ran = np.arange(15).reshape((5,3))

print(a, matrix, ones, zeros, ran, sep = "\n\n")

[3 2 1]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [5]:
print(a.shape, type(a), sep = "\n\n") #  Демонстрация атрибутов

(3,)

<class 'numpy.ndarray'>


In [6]:
# Примеры индексирования
print(a[0]) # нулевой элемент
print(a[-3]) # тот же самый элемент

# Примеры срезов
print(a[0:2]) # вывод первых двух элементов
print(a[::2]) # вывод четных индексов

3
3
[3 2]
[3 1]


In [7]:
# Примеры векторных операций
c = np.array([0,5,1])
print(a+c) # сложение
print(a-c) # вычитание
print(a*c) # умножение
print(a/c) # деление

[3 7 2]
[ 3 -3  0]
[ 0 10  1]
[inf 0.4 1. ]


C:\Users\TUF A15\AppData\Local\Temp\ipykernel_13404\289808794.py:6: RuntimeWarning: divide by zero encountered in divide
  print(a/c) # деление


In [9]:
# Примеры базовых статистик
scores = np.array([4,6,9,3,5,10,35,65,29,59,90,100])

print("Среднее: ", scores.mean())
sc_min = scores.min()
print("Минимальное: ", sc_min)
sc_max = scores.max()
print("Максимальное: ", sc_max)
print("Нормализованное: ", (scores - sc_min)/(sc_max-sc_min))

Среднее:  34.583333333333336
Минимальное:  3
Максимальное:  100
Нормализованное:  [0.01030928 0.03092784 0.06185567 0.         0.02061856 0.07216495
 0.32989691 0.63917526 0.26804124 0.57731959 0.89690722 1.        ]
